/*
 * Program Name : CEO Email Prioritizer (EECS 348 Assignment 3)
 * Description  : C++ object-oriented program that prioritizes emails for a busy
 *                CEO. It uses a MaxHeap (list/dynamic-array based, written from
 *                scratch, no pre-existing heap modules) as a priority queue.
 *                Emails are ordered by sender category
 *                (Boss > Subordinate > Peer > ImportantPerson > OtherPerson),
 *                then newest date first.
 * Inputs       : A test file (name given as argv[1] or typed at a prompt) with
 *                lines: EMAIL <category>,<subject>,<MM-DD-YYYY>, NEXT, READ, COUNT
 * Output       : Terminal output, e.g.
 *                  There are 6 emails to read.
 *                  Next email:
 *                  Sender: Boss
 *                  Subject: Never Mind
 *                  Date: 01-03-2025
 * Collaborators: None (no other people helped with the code)
 * Other sources: Initial code generated by Claude (Anthropic GenAI),
 *                https://claude.ai ; then modified.
 * Author       : Nivedita Rekha
 * Creation date: 09-30-2026
 * Revision date: 09-30-2026
 * Revisions    : (1) Output format changed to match the assignment sample
 *                    (COUNT sentence, "Next email:" header).
 *                (2) Added strict date and sender-category validation.
 *                (3) Copying of MaxHeap disabled with "= delete" (C++11).
 *                (4) Added empty-inbox messages for NEXT/READ.
 *                (5) Moved all free helper functions and command handling into
 *                    classes (EmailInbox) so the program is object-based;
 *                    main() now only creates an object and runs it.
 *                (6) Added prologue and per-block/per-line comments.
 *
 */

#include <iostream>   // cout, cerr, cin for terminal I/O
#include <fstream>    // ifstream for reading the test file
#include <string>     // std::string

using namespace std;  // avoid writing std:: everywhere

// ===========================================================================
// Email class  [Claude+Author]
// Holds one email plus the numeric keys used to compare priorities.
// ===========================================================================
class Email {
public:
    string sender;    // sender category, e.g. "Boss"
    string subject;   // subject line (may contain spaces, no commas)
    string date;      // date text in MM-DD-YYYY form
    int    priority;  // numeric rank of the category (higher = read sooner)
    int    dateKey;   // date as YYYYMMDD so dates compare as plain integers
    long   seq;       // arrival number; final tie-breaker so order is deterministic

    // Default constructor: needed because the heap allocates an array of Email
    Email() : sender(""), subject(""), date(""), priority(0), dateKey(0), seq(0) {}

    // Main constructor: stores fields and computes the comparison keys
    Email(const string& s, const string& subj, const string& d, long sequence)
        : sender(s), subject(subj), date(d), seq(sequence) {
        priority = categoryPriority(s);   // look up category rank
        dateKey  = makeDateKey(d);        // convert date text to YYYYMMDD
    }

    // True if the string is one of the five legal sender categories
    static bool validCategory(const string& c) {
        return c == "Boss" || c == "Subordinate" || c == "Peer" ||
               c == "ImportantPerson" || c == "OtherPerson";
    }

    // All priority rules live in this one method so they are easy to change.
    static int categoryPriority(const string& c) {
        if (c == "Boss")            return 5;  // read first
        if (c == "Subordinate")     return 4;  // read next
        if (c == "Peer")            return 3;  // read next
        if (c == "ImportantPerson") return 2;  // read next
        return 1;                              // OtherPerson: read last
    }

    // Returns true when d is exactly "MM-DD-YYYY" with plausible values.
    static bool validDate(const string& d) {
        if (d.size() != 10) return false;               // must be 10 characters
        for (int i = 0; i < 10; i++) {                  // check every position
            if (i == 2 || i == 5) {                     // positions of the dashes
                if (d[i] != '-') return false;
            } else if (d[i] < '0' || d[i] > '9') {      // everything else is a digit
                return false;
            }
        }
        int mm = (d[0] - '0') * 10 + (d[1] - '0');      // month value
        int dd = (d[3] - '0') * 10 + (d[4] - '0');      // day value
        return mm >= 1 && mm <= 12 && dd >= 1 && dd <= 31;  // range check
    }

    // Converts "MM-DD-YYYY" into the integer YYYYMMDD (0 if invalid).
    static int makeDateKey(const string& d) {
        if (!validDate(d)) return 0;                    // invalid dates sort oldest
        int mm   = (d[0] - '0') * 10 + (d[1] - '0');    // month
        int dd   = (d[3] - '0') * 10 + (d[4] - '0');    // day
        int yyyy = (d[6] - '0') * 1000 + (d[7] - '0') * 100 +
                   (d[8] - '0') * 10   + (d[9] - '0');  // year
        return yyyy * 10000 + mm * 100 + dd;            // combine into YYYYMMDD
    }

    // True if THIS email must be read before 'other'.
    bool higherPriorityThan(const Email& other) const {
        if (priority != other.priority) return priority > other.priority; // category first
        if (dateKey  != other.dateKey)  return dateKey  > other.dateKey;  // then newest date
        return seq < other.seq;                                           // then earlier arrival
    }
};

// ===========================================================================
// MaxHeap class  [Claude+Author]
// List-based (dynamic array) binary max-heap. The element for which
// higherPriorityThan() is "greatest" is always at index 0.
// ===========================================================================
class MaxHeap {
private:
    Email* list;      // underlying list that stores the heap
    int    count;     // number of emails currently stored
    int    capacity;  // number of slots allocated in 'list'

    // Index helpers for the implicit binary tree stored in the list
    static int parent(int i) { return (i - 1) / 2; }  // parent index
    static int left(int i)   { return 2 * i + 1; }    // left child index
    static int right(int i)  { return 2 * i + 2; }    // right child index

    // Swap two elements of the list
    void swapAt(int a, int b) {
        Email tmp = list[a];  // save a
        list[a]   = list[b];  // overwrite a with b
        list[b]   = tmp;      // put saved a into b
    }

    // Double the capacity when full: amortized O(1) per insert, O(n) space
    void grow() {
        int newCap = capacity * 2;                  // new size
        Email* bigger = new Email[newCap];          // allocate larger list
        for (int i = 0; i < count; i++)             // copy existing emails
            bigger[i] = list[i];
        delete[] list;                              // free old list
        list = bigger;                              // switch to new list
        capacity = newCap;                          // remember new size
    }

    // Move the element at i up while it outranks its parent: O(log n)
    void siftUp(int i) {
        while (i > 0 && list[i].higherPriorityThan(list[parent(i)])) {
            swapAt(i, parent(i));   // swap with parent
            i = parent(i);          // continue from parent position
        }
    }

    // Move the element at i down while a child outranks it: O(log n)
    void siftDown(int i) {
        while (true) {
            int l = left(i), r = right(i), best = i;                           // candidates
            if (l < count && list[l].higherPriorityThan(list[best])) best = l; // left better?
            if (r < count && list[r].higherPriorityThan(list[best])) best = r; // right better?
            if (best == i) break;   // heap property holds, stop
            swapAt(i, best);        // push element down one level
            i = best;               // continue from child position
        }
    }

public:
    // Constructor: start with room for 16 emails
    MaxHeap() : count(0), capacity(16) { list = new Email[capacity]; }

    // Destructor: release the list
    ~MaxHeap() { delete[] list; }

    // The heap owns raw memory, so copying is forbidden (prevents double delete)
    MaxHeap(const MaxHeap&) = delete;
    MaxHeap& operator=(const MaxHeap&) = delete;

    bool isEmpty() const { return count == 0; }   // true when no emails remain
    int  size()    const { return count; }        // number of unread emails

    // Insert an email: O(log n)
    void insert(const Email& e) {
        if (count == capacity) grow();  // make room if needed
        list[count] = e;                // place at the end
        siftUp(count);                  // restore heap order
        count++;                        // one more element
    }

    // Copy the highest-priority email into 'out' without removing it: O(1)
    bool peekMax(Email& out) const {
        if (count == 0) return false;   // nothing to look at
        out = list[0];                  // root is the max
        return true;
    }

    // Remove the highest-priority email (optionally returning it): O(log n)
    bool extractMax(Email& out) {
        if (count == 0) return false;   // nothing to remove
        out = list[0];                  // save the root
        list[0] = list[count - 1];      // move last element to the root
        count--;                        // shrink the heap
        if (count > 0) siftDown(0);     // restore heap order
        return true;
    }
};

// ===========================================================================
// EmailInbox class  [Author, restructured from Claude's main() and helpers]
// Represents the CEO's inbox. Owns the MaxHeap and executes the commands
// EMAIL, NEXT, READ and COUNT, so main() does not need any logic.
// ===========================================================================
class EmailInbox {
private:
    MaxHeap heap;      // priority queue of unread emails
    long    nextSeq;   // arrival counter handed to each new Email

    // Remove leading/trailing spaces, tabs and line endings (handles Windows files)
    static string trim(const string& s) {
        size_t a = 0, b = s.size();                                                 // window [a, b)
        while (a < b && (s[a]==' '||s[a]=='\t'||s[a]=='\r'||s[a]=='\n')) a++;       // skip front
        while (b > a && (s[b-1]==' '||s[b-1]=='\t'||s[b-1]=='\r'||s[b-1]=='\n')) b--; // skip back
        return s.substr(a, b - a);                                                  // trimmed copy
    }

    // Split "<sender>,<subject>,<date>" into its three fields; false if malformed
    static bool parseEmailFields(const string& rest, string& sender,
                                 string& subject, string& date) {
        size_t c1 = rest.find(',');                       // first comma
        if (c1 == string::npos) return false;             // missing comma
        size_t c2 = rest.find(',', c1 + 1);               // second comma
        if (c2 == string::npos) return false;             // missing comma
        sender  = trim(rest.substr(0, c1));               // text before 1st comma
        subject = trim(rest.substr(c1 + 1, c2 - c1 - 1)); // text between commas
        date    = trim(rest.substr(c2 + 1));              // text after 2nd comma
        return true;
    }

    // EMAIL command: parse, validate and enqueue one email
    void addEmail(const string& rest, const string& originalLine) {
        string sender, subject, date;                     // parsed fields
        if (parseEmailFields(rest, sender, subject, date) &&
            Email::validCategory(sender) && Email::validDate(date)) {
            heap.insert(Email(sender, subject, date, nextSeq++));  // enqueue
        } else {
            cerr << "Warning: malformed EMAIL command ignored: " << originalLine << endl;
        }
    }

    // NEXT command: show the top email but do NOT remove it
    void showNext() const {
        Email e;                                          // receives the top email
        if (heap.peekMax(e)) {
            cout << "Next email:" << endl;
            cout << "Sender: "  << e.sender  << endl;
            cout << "Subject: " << e.subject << endl;
            cout << "Date: "    << e.date    << endl;
        } else {
            cout << "There are no emails to read." << endl;
        }
    }

    // READ command: remove the top email without displaying it
    void markRead() {
        Email e;                                          // receives the removed email
        if (!heap.extractMax(e)) {
            cout << "There are no emails to read." << endl;
        }
    }

    // COUNT command: print the number of unread emails
    void showCount() const {
        cout << "There are " << heap.size() << " emails to read." << endl;
    }

public:
    // Constructor: empty inbox, sequence numbers start at 0
    EmailInbox() : nextSeq(0) {}

    // Execute one line of the test file
    void processCommand(const string& rawLine) {
        string line = trim(rawLine);                      // clean whitespace / CR characters
        if (line.empty()) return;                         // ignore blank lines

        if (line.compare(0, 6, "EMAIL ") == 0) {          // ---- EMAIL command
            addEmail(line.substr(6), line);
        } else if (line == "NEXT") {                      // ---- NEXT command
            showNext();
        } else if (line == "READ") {                      // ---- READ command
            markRead();
        } else if (line == "COUNT") {                     // ---- COUNT command
            showCount();
        } else {                                          // ---- anything else
            cerr << "Warning: unknown command ignored: " << line << endl;
        }
    }

    // Read the whole test file and execute each line; false if file cannot be opened
    bool processFile(const string& filename) {
        ifstream in(filename.c_str());                    // open the test file
        if (!in) {
            cerr << "Error: could not open file '" << filename << "'" << endl;
            return false;
        }
        string line;                                      // current line from the file
        while (getline(in, line)) {                       // process every line
            processCommand(line);
        }
        return true;
    }
};

// ===========================================================================
// main  [Author]
// Only gets the file name, creates the inbox object and tells it to run.
// ===========================================================================
int main(int argc, char* argv[]) {
    string filename;                       // name of the test file
    if (argc > 1) {                        // given on the command line?
        filename = argv[1];
    } else {                               // otherwise ask the user
        cout << "Enter test file name: ";
        getline(cin, filename);
    }

    EmailInbox inbox;                      // the CEO's inbox object
    return inbox.processFile(filename) ? 0 : 1;  // run it; non-zero exit on failure
}
